sudo: false
language: go

go:
- "1.10"
- tip

services:
  - redis-server

before_install:
- go get golang.org/x/tools/cmd/cover
# https://github.com/HewlettPackard/oneview-golang/issues/111?ts=2
# https://github.com/golang/lint/issues/397?ts=2
- go get -u golang.org/x/lint/golint

script:
- golint ./...
- go test -cover ./...
- go test -race ./...
