sudo: false
language: go

go:
- 1.8
- tip

services:
  - redis-server

before_install:
- go get golang.org/x/tools/cmd/cover
- go get -u github.com/golang/lint/golint

script:
- golint ./...
- go test -coverprofile=coverage.out .
- go tool cover -func=coverage.out
- go test ./...
- go test -race ./...
